management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  kafka:
#    consumer:
#      group-id: demo
#      auto-offset-reset: earliest
#    bootstrap-servers:
#


demo:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    input-topic: input_topic
    output-topic: output_topic
    health-check-timeout: 3s
    consumer:
      group-id: demo
      auto-offset-reset: earliest
