management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  pattern:
    dateformat: HH:mm:ss.SSSXXX

demo:
  kafka:
    enabled: true
    bootstrap-servers: localhost:9093
    input-topic: in_topic
    output-topic: out_topic
    health-check-timeout: 10s
    health-check-interval: 10s
    consumer:
      group-id: demo
      auto-offset-reset: earliest
